### ISSUE TITLE
What's the best way to install this?

### ISSUE THREAD

**Issue by alito** [AntycSolutions/django-knockout#1]
`git clone` and then `python setup.py install` don't seem to work correctly because they install an .egg, so the templates are not found at run time.

`pip install .` also doesn't seem to help.

`python setup.py develop` works, but doesn't seem correct

**Comment by Solanar** [comment]
Try `pip install git+https://github.com/AntycSolutions/django-knockout`

I also tried `git clone` + `python setup.py install` and it seemed to work. Can you provide more details?

**Comment by alito** [comment]
`pip install git+https://github.com/AntycSolutions/django-knockout` works. Thanks!

Doing a `git clone` and `python setup.py install`fails during runtime at finding the knockout/view_model.js template for me. I assume this is because the template stays packaged in the .egg and that Django can't look inside.

Here's the relevant part from the traceback:
> knockout/view_model.js
> Request Method: GET
> Request URL:    http://127.0.0.1:8000/survey
> Django Version: 1.11.6
> Exception Type: TemplateDoesNotExist
> Exception Value:    
> knockout/view_model.js
> Exception Location: /home/ale/.virtualenvs/tjuwanpa/lib/python3.5/site-packages/django/template/loader.py in get_template, line 25
> Python Executable:  /home/ale/.virtualenvs/tjuwanpa/bin/python
> Python Version: 3.5.3
> Python Path:    
> ['/home/ale/programming/web/tjuwanpa',
>  '/home/ale/programming/python/libs',
>  '/home/ale/programming/web/tjuwanpa',
>  '/home/ale/.virtualenvs/tjuwanpa/lib/python35.zip',
>  '/home/ale/.virtualenvs/tjuwanpa/lib/python3.5',
>  '/home/ale/.virtualenvs/tjuwanpa/lib/python3.5/plat-x86_64-linux-gnu',
>  '/home/ale/.virtualenvs/tjuwanpa/lib/python3.5/lib-dynload',
>  '/usr/lib/python3.5',
>  '/usr/lib/python3.5/plat-x86_64-linux-gnu',
>  '/home/ale/.virtualenvs/tjuwanpa/lib/python3.5/site-packages',
>  '/home/ale/.virtualenvs/tjuwanpa/lib/python3.5/site-packages/django_knockout-0.4.0-py3.5.egg',
>  '/home/tjuwanpa/tjuwanpa']
> Server time:    Sun, 22 Oct 2017 16:46:36 +1100
> Template-loader postmortem
> 
> Django tried loading these templates, in this order:
> 
> Using engine django:
> django.template.loaders.filesystem.Loader: /home/ale/programming/web/tjuwanpa/templates/knockout/view_model.js (Source does not exist)
> django.template.loaders.app_directories.Loader: /home/ale/.virtualenvs/tjuwanpa/lib/python3.5/site-packages/django/contrib/admin/templates/knockout/view_model.js (Source does not exist)
> django.template.loaders.app_directories.Loader: /home/ale/.virtualenvs/tjuwanpa/lib/python3.5/site-packages/django/contrib/auth/templates/knockout/view_model.js (Source does not exist)
> django.template.loaders.app_directories.Loader: /home/ale/.virtualenvs/tjuwanpa/lib/python3.5/site-packages/django/contrib/gis/templates/knockout/view_model.js (Source does not exist)
> django.template.loaders.app_directories.Loader: /home/ale/.virtualenvs/tjuwanpa/lib/python3.5/site-packages/django_filters/templates/knockout/view_model.js (Source does not exist)
> django.template.loaders.app_directories.Loader: /home/ale/.virtualenvs/tjuwanpa/lib/python3.5/site-packages/rest_framework/templates/knockout/view_model.js (Source does not exist)
> django.template.loaders.app_directories.Loader: /home/ale/.virtualenvs/tjuwanpa/lib/python3.5/site-packages/mapwidgets/templates/knockout/view_model.js (Source does not exist)
> django.template.loaders.app_directories.Loader: /home/ale/programming/web/tjuwanpa/survey/templates/knockout/view_model.js (Source does not exist)
> django.template.loaders.app_directories.Loader: /home/ale/.virtualenvs/tjuwanpa/lib/python3.5/site-packages/django_extensions/templates/knockout/view_model.js (Source does not exist)
> django.template.loaders.app_directories.Loader: /home/ale/.virtualenvs/tjuwanpa/lib/python3.5/site-packages/debug_toolbar/templates/knockout/view_model.js (Source does not exist)

**Comment by Solanar** [comment]
I've updated `setup.py` so that `python setup.py install` will work, but from my research `pip` is preferred. Please use `pip install .`  if in the same directory as `setup.py` or `pip install path/to/django-knockout` instead.

You can then use `pip uninstall django-knockout` which has no equivalent when using `setup.py`

I've updated the README

**Comment by alito** [comment]
Thank you
