### ISSUE TITLE
knockout_view_model tag does not produce right model if knockout_fields not specified

### ISSUE THREAD

**Issue by alito** [AntycSolutions/django-knockout#2]
It generates an empty `fields` array which means that every field is ignored, which then triggers binding problems.

Easiest way to see this is to remove the knockout_fields static method off the Person model in the with-django-rest-framework example.

If no exclude or include fields are specified, I'd expect it to output all the fields, or take an optional form argument and use the form's include/excluded fields.

**Comment by Solanar** [comment]
I tried to remember whether this was intentional or not and couldn't come up with a good reason. I've updated it so that it will output all fields if `knockout_fields` isn't specified.

**Comment by alito** [comment]
Works. Thanks!
